import { isProspect } from "./prospect";
import { voiceCopy } from "./voiceCopy";
import type { CustomerProfile } from "./schema";

/* =============================================================================
   voiceAgentSpec.ts — a prospect's own Qualify-and-Route configuration
   -----------------------------------------------------------------------------
   The voice workflow's CONTENT for one prospect: what the intent looks like, how the agent
   opens the call, the qualifying question and its answers, and the routing steps including
   the service-area check.

   ⚠️ **WHY AN OVERRIDE TABLE RATHER THAN GENERATED DATA.** Everything else on this screen is
   derived per prospect, and for most of them derivation is right — it costs no generation time
   and every demo on disk gets it. But an SE configuring a real agent types THESE words: the
   exact greeting, the exact ZIP codes, the exact sentence read to a caller outside the service
   area. Deriving those would be inventing them. Same pattern and same matcher as `SHAPE` and
   `SMS_SHAPE` in AgentWorkflow: keyed by prospect NAME through `isProspect`, never a guessed
   id, because these demos live in the shared library and their ids are whatever the SE typed.

   ⚠️ **EVERY PROSPECT NOW GETS THIS TEMPLATE (8/27/2026), DERIVED WHERE IT IS NOT CONFIGURED.**
   It used to return null for anyone but Comfort Keepers, and the consequence was measured
   across all 12 profiles on disk: 8 of them never asked for a ZIP and **11 never asked for a
   name**, while every one of them drew "Consumer Zip" and "Consumer Name" pills on the
   diagram. The tree advertised collecting two things the agent never collected, and nothing
   failed. `deriveVoiceSpec` closes that by building the same shape from the prospect's own
   profile, so a demo generated by any SE behaves like the configured one.

   ⚠️ **DERIVED, NOT GENERATED — no engine phase and no schema slice**, so generation time is
   unchanged and every demo already in the shared library gets it without regenerating.

   ⚠️ **AN EXPLICIT SPEC STILL WINS OUTRIGHT.** Where an SE typed the words, those are the
   words: `SPECS` is searched first and derivation only fills the gap.
   ============================================================================= */

export interface VoiceAgentSpec {
  /** Matched with `isProspect`, so any id the SE typed still resolves. */
  prospect: string;
  /** "What does this intent look like?" — the description AND the opening line. */
  intent: string;
  /** What the agent says first. Also the last of the conversation rules, as the real one has it. */
  greeting: string;
  /** The Qualify leaf's question. */
  qualifyQuestion: string;
  /** Its answers, which are also the two path nodes on the row below. */
  segments: [string, string];
  /** What the agent says when it cannot tell which answer it heard. */
  qualifyFallback: string;
  /** The intent's conversation rules, in order. */
  rules: string[];
  /**
   * ⚠️ **AN ALLOW-LIST, WHICH INVERTS THE DEMO GATE.** The generic voice prompt treats a single
   * ZIP ("12345") as the only OUT-of-area one, so every other ZIP proceeds — right for a
   * national business. This prospect serves three ZIPs and turns everything else away, so the
   * polarity is the other way round and `buildVoiceSystem` has to be told which it is.
   */
  serviceZips?: string[];
  /** Read verbatim to a caller outside the service area. */
  outOfAreaScript?: string;
  /** The Inform & Route steps, verbatim, in the SE's own numbering. */
  informSteps: string[];
}

/**
 * COMFORT KEEPERS — in-home senior care, franchised, and the caller is usually a family
 * member rather than the person receiving care. Both halves of the qualifying question matter
 * to them: arranging care AND caregiver recruitment, which is why the intent covers job
 * seekers as well as clients.
 */
const COMFORT_KEEPERS: VoiceAgentSpec = {
  prospect: "comfort keepers",
  intent:
    "The caller is reaching out about Comfort Keepers' home care services, either as a prospective client or family member interested in arranging care for themselves or a loved one, or as a job seeker interested in becoming a caregiver/employee.\n\n"
    + "This is how you should also greet and start a phone call: Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  greeting:
    "Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  qualifyQuestion:
    "Are you interested in arranging care services, or are you looking to become a caregiver with us?",
  segments: ["Looking for care services", "Interested in becoming a caregiver"],
  qualifyFallback:
    "I want to make sure I connect you with the right team. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  rules: [
    "If the caller is a prospective client or family member inquiring about care services, acknowledge their situation warmly (e.g. \"I'd be happy to help you find the right care\") before asking any qualifying questions. Many callers are inquiring on behalf of an aging parent or family member and are dealing with a difficult situation.",
    "If the caller is inquiring about caregiver employment, respond professionally and briefly acknowledge that Comfort Keepers is always looking for compassionate caregivers before moving to next steps.",
    "As soon as this intent is recognized, determine whether the caller is looking to arrange care services or is interested in becoming a caregiver, so the conversation can proceed down the correct path.",
    "When asking for the caller's zip code, explain that it's used to connect them with their local Comfort Keepers office.",
    "If asked about cost or pricing, do not provide specific numbers. Acknowledge that pricing varies by service type and location, and let the caller know the local team will cover exact pricing.",
    "This is how you should also greet and start a phone call: Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  ],
  serviceZips: ["30097", "30096", "30095"],
  outOfAreaScript:
    "Thank you for calling Comfort Keepers. Unfortunately, we don't currently serve your area, but we'd encourage you to check back with us in the future or visit comfortkeepers.com to find a nearby location.",
  /* ⚠️ VERBATIM, INCLUDING THE ORDERING. Step 3 says to turn an out-of-area caller away and
     step 5 supplies the words for it, which reads out of sequence — but it is the SE's own
     configuration and tidying it would be editing their agent rather than replicating it. */
  informSteps: [
    "1. Ask the caller for their zip code and capture it.",
    "2. Check the zip code against our current service area: 30097, 30096, 30095.",
    "3. If the zip code falls outside 30097, 30096, or 30095, politely inform the caller that we do not yet serve their area and end the call.",
    "4. If the zip code falls within our service area, ask the caller for their full name and capture it.",
    "5. If zip code does not fall within our service area say: Thank you for calling Comfort Keepers. Unfortunately, we don't currently serve your area, but we'd encourage you to check back with us in the future or visit comfortkeepers.com to find a nearby location.",
    "6. If the caller does not provide their full name, ask again before proceeding. Do not route the call without a captured full name.",
  ],
};

const SPECS: VoiceAgentSpec[] = [COMFORT_KEEPERS];

/**
 * The same Qualify-and-Route template, built from a prospect's own profile.
 *
 * ⚠️ **THE WORDING IS DELIBERATELY IDENTICAL TO WHAT THE DIAGRAM ALREADY DREW.** `intent`'s
 * FIRST LINE is `newSub` and `segments` are the exact pair `deriveTree` used as its fallback,
 * because the tree renders `intent.split("\n")[0]` as the Sales Inquiry subtitle and renders
 * `segments` as the two path nodes. Any other phrasing here would silently reword every
 * existing prospect's diagram, which is a change to screens nobody asked about.
 *
 * ⚠️ **ZIP CODES ARE NEVER INVENTED.** Comfort Keepers' three are an SE's own configuration.
 * Minting a plausible-looking allow-list for a real company would put fabricated service
 * areas in front of that company, and a caller ZIP outside it would be turned away for a
 * reason that does not exist. So `serviceZips` stays undefined here and the gate falls back to
 * the prospect's generated `serviceArea`: a real constraint when it has one, and a routing
 * lookup rather than a refusal when it does not.
 */
export function deriveVoiceSpec(profile: CustomerProfile): VoiceAgentSpec {
  const c = voiceCopy(profile);
  const name = profile.customerName;
  const booking = c.bookingLower;
  const an = /^[aeiou]/i.test(booking) ? "an" : "a";
  const area = profile.reports.agentConfig?.serviceArea?.trim();
  /* ⚠️ **`brandConversationRules` IS THE *SMS* SALES PLAYBOOK AND MUST NOT REACH THIS PROMPT.**
     The Intent drawer used to append three of them here, which was invisible while the spec
     was Comfort-Keepers-only. The moment every prospect got a spec they also reached the voice
     agent, and they read like "Qualify one at a time: ... your target price or monthly payment,
     your timeline to buy" — directly contradicting the flow's own "ASK NOTHING BEYOND THE FLOW
     ABOVE" cap. That is the over-asking already fixed once for Comfort Keepers, and a
     self-contradicting prompt is worse than either rule (see CLAUDE.md). The configured spec
     carries none of them, so deriving none is also what makes the two shapes agree.

     CONSEQUENCE, STATED: a non-configured prospect's Intent drawer now shows three rules
     rather than six. The three it loses were SMS playbook lines rendered as voice-workflow
     rules, which was wrong on that screen too. */

  const greeting =
    `Hi, thanks for calling ${name}. I'm here to help. Are you looking to book ${an} ${booking}, `
    + `or do you need help with something already in progress?`;

  /* ⚠️ THE GREETING IS ALSO THE LAST CONVERSATION RULE, exactly as the configured spec has it,
     so the drawer and the spoken opening cannot drift apart. */
  const greetingRule = `This is how you should also greet and start a phone call: ${greeting}`;

  return {
    prospect: name,
    /* Line 1 is the diagram's subtitle. Everything after it is drawer and prompt detail. */
    intent:
      `${c.newSub}\n\n`
      + `Treat them as a prospective ${c.who} and find out what they need before routing.\n\n`
      + greetingRule,
    greeting,
    qualifyQuestion:
      `Are you looking to book ${an} ${booking}, or do you need help with something already in progress?`,
    segments: [`Looking to book ${an} ${booking}`, `Needs help with an existing request`],
    qualifyFallback:
      `I want to make sure I connect you with the right team. Are you looking to book ${an} ${booking}, `
      + `or do you need help with something already in progress?`,
    rules: [
      ...(area
        ? [`When asking for the caller's zip code, explain that it is used to connect them with their local ${name} office.`]
        : [`When asking for the caller's zip code, explain that it is used to connect them with their nearest ${name} location.`]),
      `As soon as this intent is recognized, find out what the caller needs so the conversation can proceed down the correct path.`,
      `If asked about cost or pricing, do not provide specific numbers. Acknowledge that pricing varies and let the caller know the local team will cover exact pricing.`,
      greetingRule,
    ],
    /* Never invented. See the note above. */
    serviceZips: undefined,
    outOfAreaScript: area
      ? `Thank you for calling ${name}. Unfortunately we do not currently serve your area. ${name} serves ${area}.`
      : undefined,
    /* ⚠️ THE ZIP AND THE NAME ARE THE TWO PILLS THE DIAGRAM DRAWS, so these steps are what make
       the pills true. A national brand still captures the ZIP, to route to the nearest
       location rather than to turn anyone away. */
    informSteps: area
      ? [
          `1. Ask the caller for their zip code and capture it.`,
          `2. Check the zip code against our service area: ${area}.`,
          `3. If the caller is outside that service area, politely inform them and end the call without routing.`,
          `4. If the caller is inside our service area, ask for their full name and capture it.`,
          `5. If the caller is outside our service area say: Thank you for calling ${name}. Unfortunately we do not currently serve your area.`,
          `6. If the caller does not provide their full name, ask again before proceeding. Do not route the call without a captured full name.`,
        ]
      : [
          `1. Ask the caller for their zip code and capture it, so they can be matched to their nearest ${name} location.`,
          `2. Do not turn anyone away on their zip code. ${name} takes enquiries nationally.`,
          `3. Ask the caller for their full name and capture it.`,
          `4. If the caller does not provide their full name, ask again before proceeding. Do not route the call without a captured full name.`,
        ],
  };
}

/** This prospect's voice-agent spec: the SE's own where one is configured, else derived. */
export function voiceSpecFor(profile: CustomerProfile): VoiceAgentSpec {
  return SPECS.find((s) => isProspect(profile, s.prospect)) ?? deriveVoiceSpec(profile);
}
